// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('app', ['ddDragDrop', 'hljs']).controller('ApplicationController', function($scope) {
    $scope.columns = [
      {
        name: 'Header 1'
      }, {
        name: 'Header 2'
      }, {
        name: 'Header 3'
      }, {
        name: 'Header 4'
      }, {
        name: 'Header 5'
      }
    ];
    return $scope.columnDragHelper = function(columnText) {
      return "<div class='column-drag-helper'>" + (columnText.toUpperCase()) + "</div>";
    };
  });

}).call(this);
