// Generated by CoffeeScript 1.6.2
(function() {
  angular.module('app', ['Html5DragDrop', 'hljs']).controller('ApplicationController', function($scope) {
    $scope.columns = [
      {
        name: 'Header 1'
      }, {
        name: 'Header 2'
      }, {
        name: 'Header 3'
      }, {
        name: 'Header 4'
      }, {
        name: 'Header 5'
      }
    ];
    $scope.hidden = {hide: false};
    $scope.columnDragHelper = function(columnText) {
      return "<div class='column-drag-helper'>" + (columnText.toUpperCase()) + "</div>";
    };
    return $scope.dropFn = function(data, $event) {
      return console.log('dropped it!', data, $event);
    };
  });

}).call(this);
